### ISSUE TITLE
我用搜狗的2000张验证码，包含大小写字母和数字，但是训练完后只能识别出数字

### ISSUE THREAD

**Issue by weilongxiaomianjin** [cycz/EasyCaptcha#4]
如题，另外我的图片命名是z17567_1589947259.jpg这种，除此之外就全部按照配置文件的要求进行的设置了

**Comment by cycz** [comment]
字符集没写上英文吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weilongxiaomianjin"<notifications@github.com&gt;; 
发送时间: 2020年5月23日(星期六) 中午11:22
收件人: "cycz/EasyCaptcha"<EasyCaptcha@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [cycz/EasyCaptcha] 我用搜狗的2000张验证码，包含大小写字母和数字，但是训练完后只能识别出数字 (#4)





 
如题，另外我的图片命名是z17567_1589947259.jpg这种，除此之外就全部按照配置文件的要求进行的设置了

**Comment by weilongxiaomianjin** [comment]
之前是我训练集的问题，现在已经更换了，但是相比另外一个项目，我用14W素材耗时7小时，正确率能有60%左右，这个项目已经训练了十八个小时了，还在第九轮。。。并且目前打印出的识别率还不到0.7，最后我会再测试一下模型，如果成功率也不理想的话，那么这个效率问题就真的让我放弃它了...
